package pojos;
// Generated 09/06/2017 22:31:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmprestimoAlmoxarife generated by hbm2java
 */
public class EmprestimoAlmoxarife  implements java.io.Serializable {


     private Integer id;
     private String produto;
     private String funcionario;
     private Date horarioSaida;
     private Date horarioEntrada;

    public EmprestimoAlmoxarife() {
    }

    public EmprestimoAlmoxarife(String produto, String funcionario, Date horarioSaida, Date horarioEntrada) {
       this.produto = produto;
       this.funcionario = funcionario;
       this.horarioSaida = horarioSaida;
       this.horarioEntrada = horarioEntrada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public String getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(String funcionario) {
        this.funcionario = funcionario;
    }
    public Date getHorarioSaida() {
        return this.horarioSaida;
    }
    
    public void setHorarioSaida(Date horarioSaida) {
        this.horarioSaida = horarioSaida;
    }
    public Date getHorarioEntrada() {
        return this.horarioEntrada;
    }
    
    public void setHorarioEntrada(Date horarioEntrada) {
        this.horarioEntrada = horarioEntrada;
    }




}


