package pojos;
// Generated 15/06/2017 12:56:05 by Hibernate Tools 4.3.1



/**
 * Ferramentas generated by hbm2java
 */
public class Ferramentas  implements java.io.Serializable {


     private Integer id;
     private String ferramenta;
     private String situacao;
     private String usuario;
     private String obs;

    public Ferramentas() {
    }

    public Ferramentas(String ferramenta, String situacao, String usuario, String obs) {
       this.ferramenta = ferramenta;
       this.situacao = situacao;
       this.usuario = usuario;
       this.obs = obs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFerramenta() {
        return this.ferramenta;
    }
    
    public void setFerramenta(String ferramenta) {
        this.ferramenta = ferramenta;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }




}


