package pojos;
// Generated 09/06/2017 22:31:26 by Hibernate Tools 4.3.1



/**
 * Funcionarios generated by hbm2java
 */
public class Funcionarios  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String funcao;
     private int idade;
     private String endereco;
     private String telefone;
     private int rg;
     private int cpf;
     private int titulo;
     private int reservista;

    public Funcionarios() {
    }

    public Funcionarios(String nome, String funcao, int idade, String endereco, String telefone, int rg, int cpf, int titulo, int reservista) {
       this.nome = nome;
       this.funcao = funcao;
       this.idade = idade;
       this.endereco = endereco;
       this.telefone = telefone;
       this.rg = rg;
       this.cpf = cpf;
       this.titulo = titulo;
       this.reservista = reservista;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public int getRg() {
        return this.rg;
    }
    
    public void setRg(int rg) {
        this.rg = rg;
    }
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public int getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(int titulo) {
        this.titulo = titulo;
    }
    public int getReservista() {
        return this.reservista;
    }
    
    public void setReservista(int reservista) {
        this.reservista = reservista;
    }




}


