package pojos;
// Generated 15/06/2017 12:56:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OperacoesEscritorio generated by hbm2java
 */
public class OperacoesEscritorio  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private String veiculo;
     private double combustivel;
     private int isKm;
     private double valorCombustivel;
     private double horimetroAnterior;
     private double horimetroAtual;
     private double horimetroPercorrido;
     private double consumo;
     private String nota;
     private double valorPendente;
     private int isPendente;

    public OperacoesEscritorio() {
    }

    public OperacoesEscritorio(Date data, String veiculo, double combustivel, int isKm, double valorCombustivel, double horimetroAnterior, double horimetroAtual, double horimetroPercorrido, double consumo, String nota, double valorPendente, int isPendente) {
       this.data = data;
       this.veiculo = veiculo;
       this.combustivel = combustivel;
       this.isKm = isKm;
       this.valorCombustivel = valorCombustivel;
       this.horimetroAnterior = horimetroAnterior;
       this.horimetroAtual = horimetroAtual;
       this.horimetroPercorrido = horimetroPercorrido;
       this.consumo = consumo;
       this.nota = nota;
       this.valorPendente = valorPendente;
       this.isPendente = isPendente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(String veiculo) {
        this.veiculo = veiculo;
    }
    public double getCombustivel() {
        return this.combustivel;
    }
    
    public void setCombustivel(double combustivel) {
        this.combustivel = combustivel;
    }
    public int getIsKm() {
        return this.isKm;
    }
    
    public void setIsKm(int isKm) {
        this.isKm = isKm;
    }
    public double getValorCombustivel() {
        return this.valorCombustivel;
    }
    
    public void setValorCombustivel(double valorCombustivel) {
        this.valorCombustivel = valorCombustivel;
    }
    public double getHorimetroAnterior() {
        return this.horimetroAnterior;
    }
    
    public void setHorimetroAnterior(double horimetroAnterior) {
        this.horimetroAnterior = horimetroAnterior;
    }
    public double getHorimetroAtual() {
        return this.horimetroAtual;
    }
    
    public void setHorimetroAtual(double horimetroAtual) {
        this.horimetroAtual = horimetroAtual;
    }
    public double getHorimetroPercorrido() {
        return this.horimetroPercorrido;
    }
    
    public void setHorimetroPercorrido(double horimetroPercorrido) {
        this.horimetroPercorrido = horimetroPercorrido;
    }
    public double getConsumo() {
        return this.consumo;
    }
    
    public void setConsumo(double consumo) {
        this.consumo = consumo;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public double getValorPendente() {
        return this.valorPendente;
    }
    
    public void setValorPendente(double valorPendente) {
        this.valorPendente = valorPendente;
    }
    public int getIsPendente() {
        return this.isPendente;
    }
    
    public void setIsPendente(int isPendente) {
        this.isPendente = isPendente;
    }




}


