package pojos;
// Generated 15/06/2017 12:56:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OperacoesFerramentas generated by hbm2java
 */
public class OperacoesFerramentas  implements java.io.Serializable {


     private Integer id;
     private String ferramenta;
     private Date data;
     private String usuario;
     private Boolean retirada;
     private Boolean devolucao;
     private String obs;

    public OperacoesFerramentas() {
    }

    public OperacoesFerramentas(Integer id, String ferramenta, Date data, String usuario, Boolean retirada, Boolean devolucao, String obs) {
        this.id = id;
        this.ferramenta = ferramenta;
        this.data = data;
        this.usuario = usuario;
        this.retirada = retirada;
        this.devolucao = devolucao;
        this.obs = obs;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFerramenta() {
        return ferramenta;
    }

    public void setFerramenta(String ferramenta) {
        this.ferramenta = ferramenta;
    }

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Boolean getRetirada() {
        return retirada;
    }

    public void setRetirada(Boolean retirada) {
        this.retirada = retirada;
    }

    public Boolean getDevolucao() {
        return devolucao;
    }

    public void setDevolucao(Boolean devolucao) {
        this.devolucao = devolucao;
    }

    public String getObs() {
        return obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }

    @Override
    public String toString() {
        return "OperacoesFerramentas{" + "id=" + id + ", ferramenta=" + ferramenta + ", data=" + data + ", usuario=" + usuario + ", retirada=" + retirada + ", devolucao=" + devolucao + ", obs=" + obs + '}';
    }

    
   
    




}


