package pojos;
// Generated 09/06/2017 22:31:26 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * OperacoesAlmoxarife generated by hbm2java
 */
public class OperacoesAlmoxarife  implements java.io.Serializable {


     private Integer id;
     private String produto;
     private Date data;
     private double quantidadeAnterior;
     private double entrada;
     private double saida;
     private double quantidadeAtual;
     private String fornecedor;
     private String nota;
     private String destino;

    public OperacoesAlmoxarife() {
    }

    public OperacoesAlmoxarife(Integer id, String produto, Date data, double quantidadeAnterior, double entrada, double saida, double quantidadeAtual, String fornecedor, String nota, String destino) {
        this.id = id;
        this.produto = produto;
        this.data = data;
        this.quantidadeAnterior = quantidadeAnterior;
        this.entrada = entrada;
        this.saida = saida;
        this.quantidadeAtual = quantidadeAtual;
        this.fornecedor = fornecedor;
        this.nota = nota;
        this.destino = destino;
    }

    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public double getQuantidadeAnterior() {
        return this.quantidadeAnterior;
    }
    
    public void setQuantidadeAnterior(double quantidadeAnterior) {
        this.quantidadeAnterior = quantidadeAnterior;
    }
    public double getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(double entrada) {
        this.entrada = entrada;
    }
    public double getSaida() {
        return this.saida;
    }
    
    public void setSaida(double saida) {
        this.saida = saida;
    }
    public double getQuantidadeAtual() {
        return this.quantidadeAtual;
    }
    
    public void setQuantidadeAtual(double quantidadeAtual) {
        this.quantidadeAtual = quantidadeAtual;
    }
    public String getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(String fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    @Override
    public String toString() {
        return "OperacoesAlmoxarife{" + "id=" + id + ", produto=" + produto + ", data=" + data + ", quantidadeAnterior=" + quantidadeAnterior + ", entrada=" + entrada + ", saida=" + saida + ", quantidadeAtual=" + quantidadeAtual + ", fornecedor=" + fornecedor + ", nota=" + nota + ", destino=" + destino + '}';
    }
    
    

    



}


