package pojos;
// Generated 09/06/2017 22:31:26 by Hibernate Tools 4.3.1



/**
 * VeiculosLimoeiro generated by hbm2java
 */
public class VeiculosLimoeiro  implements java.io.Serializable {


     private Integer id;
     private String placa;
     private String modelo;

    public VeiculosLimoeiro() {
    }

    public VeiculosLimoeiro(String placa, String modelo) {
       this.placa = placa;
       this.modelo = modelo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }




}


